name: Java CICD
'on':
  push:
    branches:
     - main
  workflow_dispatch: {
    }
x_name: 워크플로우 기본 설정
x_description: GitHub Actions 워크플로우 이름과 트리거 조건을 설정하는 블록입니다.
jobs:
  ci-pipeline:
    runs-on: ubuntu-latest
    jobs: {
      }
    x_name: Job 설정 (Build & Test)
    x_description: 소스 체크아웃, JDK 설정, Gradle 빌드/테스트
    steps:
     -
      name: Checkout repository
      uses: actions/checkout@v4
      x_name: Checkout repository
      x_description: GitHub 저장소를 체크아웃하는 단계입니다.
      x_domain: github
      x_task:
       - checkout
     -
      name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: adopt
        java-version: '21'
      x_name: Set up JDK 21
      x_description: GitHub Actions 실행 환경에 AdoptOpenJDK 21을 설치하는 단계입니다.
      x_domain: java
      x_task:
       - setup
     -
      run: |-
        chmod +x ./gradlew
        ./gradlew clean build -x test
      name: Gradle Build (no test)
      x_name: Gradle 빌드 블록
      x_description: Gradle Wrapper에 권한을 부여하고, 테스트를 제외한 빌드만 수행합니다.
      x_domain: gradle
      x_task:
       - build
     -
      run: ./gradlew test
      name: Test with Gradle
      x_name: Gradle 테스트 실행 블록
      x_description: Gradle을 사용하여 테스트를 수행하는 블록입니다.
      x_domain: gradle
      x_task:
       - test
